"""Drift guard for the committed example dataset (R1-T9).

The files under ``examples/data`` are generated by ``examples/generate.sh``.
Because generation is deterministic, these tests regenerate every example from
its own recorded parameters (and seed) and assert the committed bytes still
match what the current generator produces. If the output format or the
generation logic changes, these tests fail -- a reminder to re-run
``examples/generate.sh`` -- so the committed examples can never silently drift.

They double as an end-to-end check of the full pipeline: generate -> serialize
-> manifest -> verify.
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from pisinger_knapsack import (
    CorrelationType,
    build_manifest,
    generate_instance,
    read_manifest,
    read_metadata,
    save_instance,
    verify_manifest,
)

EXAMPLES_DATA = Path(__file__).resolve().parent.parent / "examples" / "data"
MANIFEST_PATH = EXAMPLES_DATA / "manifest.json"
INSTANCE_FILES = sorted(p for p in EXAMPLES_DATA.glob("*.json") if p.name != "manifest.json")


def _instance_id_map() -> dict[str, Path]:
    """Map ``instance_id (stem) -> path`` for every committed instance file."""
    return {path.stem: path for path in INSTANCE_FILES}


def test_example_dataset_is_present() -> None:
    # Two sizes x three correlations, plus the manifest.
    assert len(INSTANCE_FILES) == 6
    assert MANIFEST_PATH.is_file()


@pytest.mark.parametrize("path", INSTANCE_FILES, ids=lambda p: p.stem)
def test_example_instance_regenerates_byte_identical(path: Path, tmp_path: Path) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    metadata = read_metadata(path)

    instance = generate_instance(
        np.random.default_rng(metadata["seed"]),
        n=data["n"],
        correlation_type=CorrelationType(data["correlation_type"]),
        R=data["R"],
    )
    regenerated = tmp_path / "regen.json"
    save_instance(instance, regenerated, metadata=metadata)

    assert regenerated.read_bytes() == path.read_bytes()


def test_example_manifest_matches_rebuild() -> None:
    rebuilt = build_manifest(_instance_id_map())

    assert read_manifest(MANIFEST_PATH) == rebuilt


def test_example_manifest_verifies_against_files() -> None:
    manifest = read_manifest(MANIFEST_PATH)

    assert verify_manifest(manifest, _instance_id_map()) == []
